// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Player = __t.object("Player", {
  id: __t.identity(),
  room: __t.string(),
  team: __t.u32(),
  role: __t.u32(),
  name: __t.string(),
  x: __t.f64(),
  z: __t.f64(),
  action: __t.bool(),
  seen: __t.u64(),
  online: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const Result = __t.object("Result", {
  id: __t.u64(),
  room: __t.string(),
  team: __t.u32(),
  names: __t.string(),
  timeMs: __t.u32(),
  ruleset: __t.u32(),
  created: __t.u64(),
});
export type Result = __Infer<typeof Result>;

export const Room = __t.object("Room", {
  id: __t.string(),
  host: __t.identity(),
  state: __t.string(),
  startAt: __t.u64(),
  created: __t.u64(),
});
export type Room = __Infer<typeof Room>;

export const Team = __t.object("Team", {
  id: __t.string(),
  room: __t.string(),
  number: __t.u32(),
  body: __t.string(),
  finishMs: __t.u32(),
});
export type Team = __Infer<typeof Team>;

export const Tick = __t.object("Tick", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type Tick = __Infer<typeof Tick>;

