import { chromium } from "@playwright/test";
import assert from "node:assert/strict";
const browser = await chromium.launch({ channel: "chrome", headless: true, args: ["--enable-webgl", "--ignore-gpu-blocklist"] });
const errors = [];
const pages = [];
const url = process.env.TEST_URL || "http://127.0.0.1:5173";
async function open() {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  pages.push(page);
  page.on("pageerror", e => errors.push(e.message));
  await page.routeWebSocket(u => u.port === "5173", socket => socket.close());
  await page.goto(url);
  await page.locator("canvas").waitFor();
  return page;
}
try {
  const page = await open();
  assert.equal(await page.locator("[data-role]").count(), 5);
  assert.deepEqual(await page.locator("[data-role] b").allTextContents(), ["Eyes", "Hands", "Torso", "Left Leg", "Right Leg"]);
  await page.screenshot({ path: "test-results/five-role-desktop.png" });
  await page.locator('[data-role="2"]').click();
  await page.locator("#practice").click();
  assert.equal(await page.locator("[data-role]:disabled").count(), 5);
  assert.match(await page.locator("#instruction").textContent(), /Torso/);
  await page.keyboard.press("1");
  assert.equal(await page.locator('[data-role="2"]').getAttribute("aria-pressed"), "true");
  // With no human brace, four AI teammates can reach but cannot clear the bridge.
  await page.waitForFunction(() => document.querySelector("#objective-panel").dataset.stage === "1", null, { timeout: 20000 });
  await page.waitForTimeout(1800);
  assert.equal(await page.locator("#objective-panel").getAttribute("data-stage"), "1");
  await page.keyboard.down(" ");
  await page.locator("#finish-dialog").waitFor({ state: "visible", timeout: 60000 });
  await page.keyboard.up(" ");
  assert.match(await page.locator("#finish-label").textContent(), /UNRANKED/);
  assert.equal(await page.locator("#objective-panel").getAttribute("data-stage"), "6");
  await page.screenshot({ path: "test-results/five-role-practice-finish.png" });
  await page.locator('[data-close="finish-dialog"]').click();
  await page.locator("#exit").click();
  assert.equal(await page.locator("[data-role]:disabled").count(), 0);
  assert.equal(await page.locator("#join").isDisabled(), false);
  const code = "UI" + Date.now().toString().slice(-8);
  for (let i=0;i<5;i++) {
    const p = i === 0 ? page : await open();
    await p.locator("#open-lobby").click();
    await p.waitForFunction(() => document.querySelector("#connection").textContent === "SPACETIMEDB CONNECTED");
    await p.locator("#name").fill("UI " + i);
    await p.locator("#code").fill(code);
    await p.locator("#part").selectOption(String(i));
    await p.locator("#join").click();
    await p.locator("#members").getByText("UI " + i, { exact: false }).waitFor();
    if (i === 0) assert.equal(await p.locator("#start").isDisabled(), true);
  }
  await page.waitForFunction(() => !document.querySelector("#start").disabled);
  await page.locator("#start").click();
  await page.waitForFunction(() => document.body.classList.contains("playing"));
  assert.equal(await page.locator("[data-role]:disabled").count(), 5);
  await page.keyboard.press("5");
  assert.equal(await page.locator('[data-role="0"]').getAttribute("aria-pressed"), "true");
  await page.locator("#room-panel").click();
  assert.equal(await page.locator("#part").isDisabled(), true);
  assert.equal(await page.locator("#team").isDisabled(), true);
  assert.equal(await page.locator("#join").isDisabled(), true);
  await page.locator('[data-close="lobby"]').click();
  await page.waitForFunction(() => document.querySelector("#race-status").textContent === "RACING");
  await page.screenshot({ path: "test-results/five-role-multiplayer.png" });
  // Reload uses the same session token and resumes exactly the server assignment.
  await page.reload();
  await page.waitForFunction(() => document.body.classList.contains("playing"));
  assert.equal(await page.locator('[data-role="0"]').getAttribute("aria-pressed"), "true");
  for (const p of pages) await p.locator("#exit").click();
  const mobile = await open();
  await mobile.setViewportSize({ width: 390, height: 844 });
  await mobile.locator('[data-role="2"]').click();
  await mobile.locator("#practice").click();
  assert.equal(await mobile.locator(".touch .grab").textContent(), "BRACE");
  assert.equal(await mobile.locator("#objective-panel").isVisible(), true);
  await mobile.screenshot({ path: "test-results/five-role-mobile.png" });
  const overflow = await mobile.evaluate(() => document.documentElement.scrollWidth > innerWidth);
  assert.equal(overflow, false);
  const touchBox = await mobile.locator(".touch .grab").boundingBox();
  await mobile.mouse.move(touchBox.x + 10, touchBox.y + 10);
  await mobile.mouse.down();
  await mobile.waitForFunction(() => document.querySelector("#role-feedback").textContent.includes("BRACED"));
  assert.match(await mobile.locator("#role-feedback").textContent(), /BRACED/);
  await mobile.mouse.up();
  await mobile.locator("#room-panel").click();
  assert.equal(await mobile.locator("#part").isDisabled(), false);
  assert.equal(await mobile.locator("#join").isDisabled(), false);
  assert.deepEqual(errors, []);
  console.log("PASS: five-role desktop/mobile UI, human-required practice completion, keyboard/card/lobby locks, five-client readiness, countdown and reload reconnect; no page errors.");
} finally { await browser.close(); }
