// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import InputReducer from "../input_reducer";
import JoinReducer from "../join_reducer";
import LeaveReducer from "../leave_reducer";
import StartReducer from "../start_reducer";

export type InputParams = __Infer<typeof InputReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type LeaveParams = __Infer<typeof LeaveReducer>;
export type StartParams = __Infer<typeof StartReducer>;

